const bemLikeClassPattern =
  '^(?:' +
  '[a-z][a-z0-9]*(?:-[a-z0-9]+)*' +
  '(?:__(?:[a-z0-9]+(?:-[a-z0-9]+)*))?' +
  '(?:--(?:[a-z0-9]+(?:-[a-z0-9]+)*))?' +
  '|' +
  '(?:is|has|js|theme)-[a-z0-9]+(?:-[a-z0-9]+)*' +
  ')$'

const tailwindAtRules = [
  'tailwind',
  'apply',
  'layer',
  'config',
  'theme',
  'utility',
  'variant',
  'custom-variant',
  'plugin',
  'source',
]

const propertiesOrder = [
  'content',
  'position',
  'inset',
  'inset-block',
  'inset-block-start',
  'inset-block-end',
  'inset-inline',
  'inset-inline-start',
  'inset-inline-end',
  'top',
  'right',
  'bottom',
  'left',
  'z-index',
  'display',
  'visibility',
  'opacity',
  'overflow',
  'overflow-x',
  'overflow-y',
  'clip',
  'clip-path',
  'flex',
  'flex-grow',
  'flex-shrink',
  'flex-basis',
  'flex-direction',
  'flex-wrap',
  'grid',
  'grid-template',
  'grid-template-columns',
  'grid-template-rows',
  'grid-auto-flow',
  'grid-auto-columns',
  'grid-auto-rows',
  'grid-column',
  'grid-row',
  'order',
  'align-items',
  'align-content',
  'align-self',
  'justify-items',
  'justify-content',
  'justify-self',
  'place-items',
  'place-content',
  'place-self',
  'gap',
  'row-gap',
  'column-gap',
  'width',
  'min-width',
  'max-width',
  'height',
  'min-height',
  'max-height',
  'inline-size',
  'min-inline-size',
  'max-inline-size',
  'block-size',
  'min-block-size',
  'max-block-size',
  'aspect-ratio',
  'margin',
  'margin-block',
  'margin-block-start',
  'margin-block-end',
  'margin-inline',
  'margin-inline-start',
  'margin-inline-end',
  'margin-top',
  'margin-right',
  'margin-bottom',
  'margin-left',
  'padding',
  'padding-block',
  'padding-block-start',
  'padding-block-end',
  'padding-inline',
  'padding-inline-start',
  'padding-inline-end',
  'padding-top',
  'padding-right',
  'padding-bottom',
  'padding-left',
  'border',
  'border-width',
  'border-style',
  'border-color',
  'border-block',
  'border-inline',
  'border-top',
  'border-right',
  'border-bottom',
  'border-left',
  'border-radius',
  'outline',
  'background',
  'background-color',
  'background-image',
  'background-position',
  'background-size',
  'background-repeat',
  'box-shadow',
  'color',
  'font',
  'font-family',
  'font-size',
  'font-style',
  'font-weight',
  'line-height',
  'letter-spacing',
  'text-align',
  'text-decoration',
  'text-transform',
  'text-rendering',
  'text-wrap',
  'white-space',
  'vertical-align',
  'appearance',
  'cursor',
  'pointer-events',
  'user-select',
  'resize',
  'object-fit',
  'transform',
  'transition',
]

export default {
  extends: [
    'stylelint-config-standard',
    'stylelint-config-standard-scss',
  ],

  plugins: ['stylelint-order'],

  ignoreFiles: [
    '**/node_modules/**',
    '**/dist/**',
    '**/public/**',
    '**/.git/**',
  ],

  rules: {
    'no-empty-source': null,
    'no-descending-specificity': null,
    'declaration-no-important': null,

    'color-function-notation': 'modern',
    'alpha-value-notation': 'percentage',

    'custom-property-pattern': '^[a-z0-9-]+$',
    'keyframes-name-pattern': '^[a-z0-9-]+$',

    'selector-class-pattern': [
      bemLikeClassPattern,
      {
        resolveNestedSelectors: true,
        message:
          'Use kebab-case BEM classes (`block`, `block__element`, `block--modifier`) or service/state prefixes (`is-*`, `has-*`, `js-*`, `theme-*`).',
      },
    ],

    'selector-max-id': 0,
    'selector-max-compound-selectors': 4,
    'max-nesting-depth': 4,

    'order/properties-order': [
      propertiesOrder,
      {
        unspecified: 'bottomAlphabetical',
      },
    ],

    'at-rule-no-unknown': null,
    'scss/at-rule-no-unknown': true,
    'scss/at-if-no-null': true,
    'scss/dollar-variable-pattern': '^[a-z0-9-]+$',
    'scss/at-function-pattern': '^[a-z0-9-]+$',
    'scss/at-mixin-pattern': '^[a-z0-9-]+$',
    'scss/percent-placeholder-pattern': '^[a-z0-9-]+$',
    'scss/selector-no-redundant-nesting-selector': true,
  },

  overrides: [
    {
      files: ['src/styles/tailwind.css'],
      rules: {
        'at-rule-no-unknown': [
          true,
          {
            ignoreAtRules: tailwindAtRules,
          },
        ],
        'scss/at-rule-no-unknown': null,
      },
    },
  ],
}
